name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  cicd:
    uses: ./.github/workflows/cicd.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::762233753798:role/GithubActions_LinkShortner_Role"
      aws-region: "us-east-2"
      aws-statefile-s3-bucket: "terraform-762233753798-statefile"
      aws-lock-dynamodb-table: "terraform-lock"