name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  cicd:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::762233753798:role/GithubActions_LinkShortner_Role"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "terraform-762233753798-statefile "
      aws-lock-dynamodb-table: "terraform-lock"